server.port=${PORT:50051}
spring.application.name=paymentservice
mysql.host=${MYSQL_HOST:mysql-payment}
mysql.port=${MYSQL_PORT:3306}
mysql.user=${MYSQL_USER:paymentuser}
mysql.password=${MYSQL_PASSWORD:paymentpassword}
mysql.database=${MYSQL_DATABASE:paymentdb}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,prometheus
management.prometheus.metrics.export.enabled=true

# HTTP server latency histogram
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=50ms,100ms,250ms,500ms,1s,2s
