FROM maven:3.9-eclipse-temurin-21-alpine AS builder
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:resolve -B

COPY src ./src
RUN mvn package -DskipTests -B

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app
COPY --from=builder /app/target/apigateway.jar /app/apigateway.jar

EXPOSE 9090
ENTRYPOINT ["java", "-jar", "/app/apigateway.jar"]
