apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: tangnhatdang/ecommerce-kltn-apigateway:b77dd8a
          ports:
            - containerPort: 9090
          env:
            - name: PORT
              value: "9090"
            - name: AUTH_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: AUTH_SERVICE_ADDR
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PRODUCT_CATALOG_SERVICE_ADDR
            - name: CART_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: CART_SERVICE_ADDR
            - name: CHECKOUT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: CHECKOUT_SERVICE_ADDR
            - name: PAYMENT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PAYMENT_SERVICE_ADDR
            - name: SHIPPING_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SHIPPING_SERVICE_ADDR
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: app
spec:
  selector:
    app: apigateway
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
