apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: tangnhatdang/ecommerce-kltn-cartservice:cd1baf6
          ports:
            - containerPort: 7070
          env:
            - name: PORT
              value: "7070"
            - name: REDIS_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: REDIS_ADDR
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 7070
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 7070
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: app
  labels:
    app: spring-service
spec:
  selector:
    app: cartservice
  ports:
    - name: http
      port: 7070
      targetPort: 7070
  type: ClusterIP
