apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: app
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: checkoutservice
          image: tangnhatdang/ecommerce-kltn-checkoutservice:0b42cf5
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PRODUCT_CATALOG_SERVICE_ADDR
            - name: SHIPPING_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SHIPPING_SERVICE_ADDR
            - name: PAYMENT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PAYMENT_SERVICE_ADDR
            - name: CART_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: CART_SERVICE_ADDR
            - name: MONGO_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MONGO_ADDR
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 5050
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 5050
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: app
  labels:
    app: spring-service
spec:
  selector:
    app: checkoutservice
  ports:
    - name: http
      port: 5050
      targetPort: 5050
  type: ClusterIP
