apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tangnhatdang/ecommerce-kltn-frontend:bbd64e0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PRODUCT_CATALOG_SERVICE_ADDR
            - name: CART_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: CART_SERVICE_ADDR
            - name: SHIPPING_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SHIPPING_SERVICE_ADDR
            - name: CHECKOUT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: CHECKOUT_SERVICE_ADDR
            - name: AUTH_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: AUTH_SERVICE_ADDR
            - name: API_GATEWAY_ADDR
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: API_GATEWAY_ADDR
            - name: ENABLE_PROFILER
              value: "0"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
